ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-parrotos-7"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install

# Startup Scripts
COPY ./src/ubuntu/install/dind/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind/dockerd.conf /etc/supervisor/conf.d/
COPY ./src/ubuntu/install/dind/daemon.json /etc/docker/daemon.json

# Copy install scripts
COPY ./src/ubuntu/install $INST_DIR

### Install DinD
RUN bash $INST_DIR/dind/install_dind.sh  || exit 1;

### Install Tools
RUN bash $INST_DIR/tools/install_tools_deluxe.sh  || exit 1;

# Install Utilities
RUN bash $INST_DIR/misc/install_tools.sh || exit 1;

### Install Alias CLI
RUN bash $INST_DIR/tools/install_alias_cli.sh  || exit 1;

### Install JetBrains Reset Trial
RUN bash $INST_DIR/tools/install_jetbrains_reset_trial.sh  || exit 1;

# Install Node
RUN bash $INST_DIR/tools/install_node.sh  || exit 1;

### Install Java
RUN apt-get update && apt-get install -y default-jdk default-jre

# Install Terraform
RUN bash $INST_DIR/terraform/install_terraform.sh  || exit 1;

# Install Firefox
RUN bash $INST_DIR/firefox/install_firefox.sh  || exit 1;

# Install Brave
RUN bash $INST_DIR/brave/install_brave.sh  || exit 1;

### Install Visual Studio Code
RUN bash $INST_DIR/vs_code/install_vs_code.sh  || exit 1;

### Install IntelliJ
RUN bash $INST_DIR/intellij/install_intellij.sh || exit 1;

# Install Postman
RUN bash $INST_DIR/postman/install_postman.sh  || exit 1;

### Install Parrot
RUN bash $INST_DIR/parrot/install_parrot.sh  || exit 1;

# Install Cleanup
RUN bash $INST_DIR/cleanup/cleanup.sh  || exit 1;

RUN $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
