ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

# Rootless Dind
COPY ./src/ubuntu/install/dind_rootless/install_dind_rootless.sh $INST_SCRIPTS/dind_rootless/
RUN bash $INST_SCRIPTS/dind_rootless/install_dind_rootless.sh
RUN rm -rf $INST_SCRIPTS/dind_rootless
COPY ./src/ubuntu/install/dind_rootless/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh && chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind_rootless/modprobe /usr/local/bin/modprobe
RUN chmod +x /usr/local/bin/modprobe
ENV XDG_RUNTIME_DIR=/docker \
    DOCKER_HOST=unix:///docker/docker.sock
RUN mkdir -p $XDG_RUNTIME_DIR && chown 1000:0 $XDG_RUNTIME_DIR && \
    mkdir -p /home/kasm-user/.config/docker && \
    chown -R 1000:0 /home/kasm-user/.config
COPY ./src/ubuntu/install/dind_rootless/daemon.json /home/kasm-user/.config/docker/daemon.json
RUN chown 1000:0 /home/kasm-user/.config/docker/daemon.json

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install

# Copy install scripts
COPY ./src/ubuntu/install $INST_DIR

### Install Tools
RUN bash $INST_DIR/tools/install_tools_deluxe.sh  || exit 1;

# Install Utilities
RUN bash $INST_DIR/misc/install_tools.sh || exit 1;

### Install Alias CLI
RUN bash $INST_DIR/tools/install_alias_cli.sh  || exit 1;

### Install JetBrains Reset Trial
RUN bash $INST_DIR/tools/install_jetbrains_reset_trial.sh  || exit 1;

# Install Node
RUN bash $INST_DIR/tools/install_node.sh  || exit 1;

# Install Google Chrome
RUN bash $INST_DIR/chrome/install_chrome.sh  || exit 1;

# Install Chromium
RUN bash $INST_DIR/chromium/install_chromium.sh  || exit 1;

### Install Visual Studio Code
RUN bash $INST_DIR/vs_code/install_vs_code.sh  || exit 1;

### Install Java
#RUN apt-get update && apt-get install -y default-jdk default-jre

### Install IntelliJ
RUN bash $INST_DIR/intellij/install_intellij.sh || exit 1;

# Install Postman
RUN bash $INST_DIR/postman/install_postman.sh  || exit 1;

# Install Webstorm
RUN bash $INST_DIR/webstorm/install_webstorm.sh  || exit 1;

# Install Cleanup
RUN bash $INST_DIR/cleanup/cleanup.sh  || exit 1;


RUN  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]

