ARG BASE_TAG="develop"
ARG BASE_IMAGE="kasm-core-macchiato-noble"
FROM macchiato23/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please"

# DinD
COPY ./src/ubuntu/install/dind/install_dind.sh $INST_SCRIPTS/dind/
RUN bash $INST_SCRIPTS/dind/install_dind.sh && rm -rf $INST_SCRIPTS/dind/
COPY ./src/ubuntu/install/dind/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind/dockerd.conf /etc/supervisor/conf.d/
COPY ./src/ubuntu/install/dind/daemon.json /etc/docker/daemon.json

# Base tools
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/

# Tools (deluxe, alias CLI, JetBrains reset trial, Node, Claude Code)
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/install_tools_deluxe.sh && \
    bash $INST_SCRIPTS/tools/install_alias_cli.sh && \
    bash $INST_SCRIPTS/tools/install_jetbrains_reset_trial.sh && \
    bash $INST_SCRIPTS/tools/install_node.sh && \
    bash $INST_SCRIPTS/tools/install_claude_code.sh && \
    rm -rf $INST_SCRIPTS/tools/

# Brave Browser
COPY ./src/ubuntu/install/brave/ $INST_SCRIPTS/brave/
RUN bash $INST_SCRIPTS/brave/install_brave.sh && rm -rf $INST_SCRIPTS/brave/

# VS Code
COPY ./src/ubuntu/install/vs_code/ $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_vs_code.sh && rm -rf $INST_SCRIPTS/vs_code/

# Java & Maven
RUN apt-get update && apt-get install -y default-jdk default-jre maven && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# IntelliJ IDEA
COPY ./src/ubuntu/install/intellij/ $INST_SCRIPTS/intellij/
RUN bash $INST_SCRIPTS/intellij/install_intellij.sh && rm -rf $INST_SCRIPTS/intellij/

# Postman
COPY ./src/ubuntu/install/postman/ $INST_SCRIPTS/postman/
RUN bash $INST_SCRIPTS/postman/install_postman.sh && rm -rf $INST_SCRIPTS/postman/

# Thunderbird
COPY ./src/ubuntu/install/thunderbird/ $INST_SCRIPTS/thunderbird/
RUN bash $INST_SCRIPTS/thunderbird/install_thunderbird.sh && rm -rf $INST_SCRIPTS/thunderbird/

# Terraform
COPY ./src/ubuntu/install/terraform/ $INST_SCRIPTS/terraform/
RUN bash $INST_SCRIPTS/terraform/install_terraform.sh && rm -rf $INST_SCRIPTS/terraform/

# GCP Cloud SDK
COPY ./src/ubuntu/install/cloud_sdk/ $INST_SCRIPTS/cloud_sdk/
RUN bash $INST_SCRIPTS/cloud_sdk/install_gcp_sdk.sh && rm -rf $INST_SCRIPTS/cloud_sdk/

# Cleanup
COPY ./src/ubuntu/install/cleanup $INST_SCRIPTS/cleanup/
RUN bash $INST_SCRIPTS/cleanup/cleanup.sh && rm -rf $INST_SCRIPTS/cleanup/

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]
