ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-parrotos-7"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install


### Install Parrot
COPY ./src/ubuntu/install/parrot $INST_DIR/parrot/
RUN bash $INST_DIR/parrot/install_parrot.sh  || exit 1;

### Copy install tools
COPY ./src/ubuntu/install/tools $INST_DIR/tools/

### Install Alias CLI
RUN bash $INST_DIR/tools/install_alias_cli.sh  || exit 1;

### Install JetBrains Reset Trial
RUN bash $INST_DIR/tools/install_jetbrains_reset_trial.sh  || exit 1;

# Install Node
RUN bash $INST_DIR/tools/install_node.sh  || exit 1;

# Install Firefox
COPY ./src/ubuntu/install/firefox $INST_DIR/firefox/
RUN bash $INST_DIR/firefox/install_firefox.sh  || exit 1;

# Install Brave
COPY ./src/ubuntu/install/brave $INST_DIR/brave/
RUN bash $INST_DIR/brave/install_brave.sh  || exit 1;

### Install Thunderbird
COPY ./src/ubuntu/install/thunderbird $INST_DIR/thunderbird/
RUN bash $INST_DIR/thunderbird/install_thunderbird.sh  || exit 1;

### Install Visual Studio Code
COPY ./src/ubuntu/install/vs_code $INST_DIR/vs_code/
RUN bash $INST_DIR/vs_code/install_vs_code.sh  || exit 1;

### Install IntelliJ
COPY ./src/ubuntu/install/intellij $INST_DIR/intellij/
RUN bash $INST_DIR/intellij/install_intellij.sh || exit 1;

# Rootless Dind
COPY ./src/ubuntu/install/dind_rootless/install_dind_rootless.sh $INST_SCRIPTS/dind_rootless/
RUN bash $INST_SCRIPTS/dind_rootless/install_dind_rootless.sh
RUN rm -rf $INST_SCRIPTS/dind_rootless
COPY ./src/ubuntu/install/dind_rootless/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh && chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind_rootless/modprobe /usr/local/bin/modprobe
RUN chmod +x /usr/local/bin/modprobe
ENV XDG_RUNTIME_DIR=/docker \
    DOCKER_HOST=unix:///docker/docker.sock
RUN mkdir -p $XDG_RUNTIME_DIR && chown 1000:0 $XDG_RUNTIME_DIR && \
    mkdir -p /home/kasm-user/.config/docker && \
    chown -R 1000:0 /home/kasm-user/.config
COPY ./src/ubuntu/install/dind_rootless/daemon.json /home/kasm-user/.config/docker/daemon.json
RUN chown 1000:0 /home/kasm-user/.config/docker/daemon.json

# Install Cleanup
COPY ./src/ubuntu/install/cleanup $INST_DIR/cleanup/
RUN bash $INST_DIR/cleanup/cleanup.sh  || exit 1;

RUN $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
