services:
#    lm-studio:
#        build:
#            context: .
#            dockerfile: dockerfile-macchiato-lmstudio
#        image: macchiato23/kasm-lm-studio:latest
#        shm_size: 512m
#        ports:
#            - "6902:6901"
#        environment:
#            VNC_PW: password
    development:
        build:
            context: .
            dockerfile: dockerfile-macchiato-development
        image: macchiato23/kasm-development:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password
    amnesia-desktop:
        build:
            context: .
            dockerfile: dockerfile-macchiato-amnesia-desktop
        image: macchiato23/kasm-amnesia-desktop:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password
    parrot:
        build:
            context: .
            dockerfile: dockerfile-macchiato-parrotos-7
        image: macchiato23/kasm-parrotos-7:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password
    parrot-rootless:
        build:
            context: .
            dockerfile: dockerfile-macchiato-parrotos-7-rootless
        image: macchiato23/kasm-parrotos-7-rootless:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password
    windows:
        build:
            context: .
            dockerfile: dockerfile-macchiato-windows
        image: macchiato23/kasm-windows:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password
    big-sur:
        build:
            context: .
            dockerfile: dockerfile-macchiato-big-sur
        image: macchiato23/kasm-big-sur:latest
        shm_size: 512m
        ports:
            - "6902:6901"
        environment:
            VNC_PW: password