ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please"

# Base tools
COPY ./src/ubuntu/install/misc $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/install_tools.sh && rm -rf $INST_SCRIPTS/misc/

# Alias CLI tool
COPY ./src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/install_alias_cli.sh && rm -rf $INST_SCRIPTS/tools/

# GTK theme build dependencies
RUN apt-get install -y sassc gtk2-engines-murrine git

# Win11 GTK + Window Manager Theme — system-wide (/usr/share/themes when run as root)
RUN git clone --depth=1 https://github.com/yeyushengfan258/Win11-gtk-theme.git /tmp/Win11-gtk-theme && \
    cd /tmp/Win11-gtk-theme && \
    ./install.sh -d /usr/share/themes -l --tweaks float round blur && \
    rm -rf /tmp/Win11-gtk-theme

# Win11 Icon Theme — system-wide (/usr/share/icons when run as root)
RUN git clone --depth=1 https://github.com/yeyushengfan258/Win11-icon-theme.git /tmp/Win11-icon-theme && \
    cd /tmp/Win11-icon-theme && \
    ./install.sh && \
    rm -rf /tmp/Win11-icon-theme

# Segoe UI fonts + apply Win11 theme/font to XFCE profile config
COPY ./src/ubuntu/install/windows $INST_SCRIPTS/windows/
RUN bash $INST_SCRIPTS/windows/configure_xfce.sh && rm -rf $INST_SCRIPTS/windows/

# Cleanup
COPY ./src/ubuntu/install/cleanup $INST_SCRIPTS/cleanup/
RUN bash $INST_SCRIPTS/cleanup/cleanup.sh && rm -rf $INST_SCRIPTS/cleanup/

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]
